### ISSUE TITLE
Debugger not working, throwing undefined method error

### ISSUE THREAD

**Issue by tomdracz** [socketry/async-debug#2]
Trying out the Google example in the repo, just changing the require to point at the debug gem as below:

```
require 'async'
require 'async/http/internet'
require 'async/debug'

terms = %w{thoughtful fear size payment lethal modern recognise face morning sulky mountainous contain science snow uncle skirt truthful door travel snails closed rotten halting creator teeny-tiny beautiful cherries unruly level follow strip team things suggest pretty warm end cannon bad pig consider airport strengthen youthful fog three walk furry pickle moaning fax book ruddy sigh plate cakes shame stem faulty bushes dislike train sleet one colour behavior bitter suit count loutish squeak learn watery orange idiotic seat wholesale omniscient nostalgic arithmetic instruct committee puffy program cream cake whistle rely encourage war flagrant amusing fluffy prick utter wacky occur daily son check}

class Google < Protocol::HTTP::Middleware
	def search(term)
		Console.logger.info(self) {"Searching for #{term}..."}
		
		self.get("/search?q=#{term}", {"user-agent" => "Hi Google :)"})
	end
end

Async(annotation: "Parent") do |task|
	Async::Debug.serve
	
	endpoint = Async::HTTP::Endpoint.parse("https://www.google.com")
	client = Async::HTTP::Client.new(endpoint)
	google = Google.new(client)
	
	semaphore = Async::Semaphore.new(8)
	
	results = terms.map do |term|
		semaphore.async(annotation: "Fetching #{term}") do |task|
			response = google.search(term)
			[term, response.read.scan(term).count]
		end
	end
	
	sleep 1
	task.reactor.print_hierarchy
	
	results = results.map(&:wait)
	
	pp results
end
```

Throws an error coming from the console gem:
```
/Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/console-1.17.2/lib/console/terminal/logger.rb:152:in `default_suffix': undefined method `size' for Async::Debug:Module (NoMethodError)

					if annotation = Fiber.current.annotation and annotation.size > 0
```

Tested this on Ruby 3.2.2 and Ruby 3.1.1, running on M1 Mac.

Full backtrace below:
```
/Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/console-1.17.2/lib/console/terminal/logger.rb:152:in `default_suffix': undefined method `size' for Async::Debug:Module (NoMethodError)

					if annotation = Fiber.current.annotation and annotation.size > 0
					                                                       ^^^^^
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/console-1.17.2/lib/console/terminal/logger.rb:172:in `format_object_subject'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/console-1.17.2/lib/console/terminal/logger.rb:144:in `format_subject'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/console-1.17.2/lib/console/terminal/logger.rb:98:in `call'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/console-1.17.2/lib/console/filter.rb:130:in `call'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/console-1.17.2/lib/console/filter.rb:29:in `block (3 levels) in []'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-2.6.2/lib/async/task.rb:312:in `failed!'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-2.6.2/lib/async/task.rb:355:in `rescue in block in schedule'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-2.6.2/lib/async/task.rb:352:in `block in schedule'
/Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/console-1.17.2/lib/console/terminal/logger.rb:152:in `default_suffix': undefined method `size' for Async::Debug:Module (NoMethodError)

					if annotation = Fiber.current.annotation and annotation.size > 0
					                                                       ^^^^^
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/console-1.17.2/lib/console/terminal/logger.rb:184:in `format_string_subject'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/console-1.17.2/lib/console/terminal/logger.rb:142:in `format_subject'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/console-1.17.2/lib/console/terminal/logger.rb:98:in `call'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/console-1.17.2/lib/console/filter.rb:130:in `call'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/console-1.17.2/lib/console/filter.rb:29:in `block (3 levels) in []'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-debug-0.2.0/lib/async/debug.rb:43:in `block in serve'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-2.6.2/lib/async/task.rb:180:in `block in run'
	from /Users/tom.dracz/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-2.6.2/lib/async/task.rb:350:in `block in schedule'
```

**Comment by tomdracz** [comment]
FWIW I've managed to get this to work by pinning `console` gem to version `1.16.2` which was released around the similar-ish time to the last release of `async-debug`. Looks like some subsequent version of `console` changed something that breaks the debug behaviour here
